### ISSUE TITLE
No output text file created in Windows 10

### ISSUE THREAD

**Issue by jayantanth** [Parathantl/tesseract_gui#7]
![Capture](https://user-images.githubusercontent.com/1370149/85920032-e760c600-b88d-11ea-8f8f-492d84dc23fe.PNG)
![Capture2](https://user-images.githubusercontent.com/1370149/85920035-e92a8980-b88d-11ea-819f-75dc35b44a4b.PNG)
 Used it is created only single PDF file, but no text file created in text folder. No page by page images created in JPG folder,

**Comment by Parathantl** [comment]
@jayantanth Can you please test again by removing the spaces in the folder name?
Eg: **Requested book** to **Requestedbook**

If that worked fine. Please let me know. I have done other changes too. 
So, that I can remove this bug from the program and release another one.

**Comment by Parathantl** [comment]
@jayantanth Can you please try again by removing spaces in the folder's name.
**Requested book** to **Requestedbook** 

I think this one is the bug.
If it is please let me know.

I will try to fix it ASAP.

**Comment by jayantanth** [comment]
![Capture](https://user-images.githubusercontent.com/1370149/85927589-c4053d80-b8c4-11ea-8b16-9b5107f0d596.PNG)
![Capture2](https://user-images.githubusercontent.com/1370149/85927591-c5cf0100-b8c4-11ea-93c0-f9f89f1cd87c.PNG)

Yahh... Now its works.. Just space of the folder name, creating the issues.

**Comment by jayantanth** [comment]
Although, this is a separate request: Could It be possible to create one text file to add all of the text output??

**Comment by jayantanth** [comment]
![Capture3](https://user-images.githubusercontent.com/1370149/85927764-d16ef780-b8c5-11ea-80cf-15df0848a112.PNG)
OCR Output of Bengali Language is quite good now.

**Comment by Parathantl** [comment]
Great. I am currently working on this feature to output all text files as a single text file. I will release it once I finished it.

**Comment by jayantanth** [comment]
> Great. I am currently working on this feature to output all text files as a single text file. I will release it once I finished it.

Ok That's great, although  I have found the solution as simple in the command line in windows, ` copy *.txt output.txt`  in the folder.

**Comment by Parathantl** [comment]
Could you please check whether the solution is selecting the pages in the correct order?
Example: Page 1, Page 2

I think mostly it will be like page 1, page 10, page 100 something like that. Please check it and let me know.

**Comment by jayantanth** [comment]
![Capture5](https://user-images.githubusercontent.com/1370149/85942354-513ca680-b946-11ea-87a1-c42f49da86bc.PNG)
 Yes it is creating a new issue of file number, so you need to create file number in last four-digit to solve this issue.  Page_0001, Page_0999 as like that.

**Comment by Parathantl** [comment]
@jayantanth The new release resolves the white space name issue and creates a final single output text file inside the folder. **Please check it and let me know**. In the new release just **download as ZIP** and run the **setup.bat** file by clicking on it.

If you have already set up all the necessary modules just execute the **Tesseract_GUI_Tool** app in the folder itself.

**Comment by jayantanth** [comment]
Checked. Now the issue is when I click on "start" the application is closed., Only three file created in Folder
![Capture](https://user-images.githubusercontent.com/1370149/86401524-fc8f8780-bcc7-11ea-893a-8fa5d0c92bb6.PNG)

**Comment by jayantanth** [comment]
Oho... I have uninstalled all, again Install old version v_0.2, the same issue found, the application closed without any messages.
I am using the same machine. I have installed anything new OR haven't change any system last 2 month. But this application closed. Don't know why.

**Comment by Parathantl** [comment]
Download the Version 0.3 ZIPPED file. Then Extract it.

After that click on the **setup.bat** file. It will ask you to download Python, Tesseract and ghost Script in the order. Install them if you have uninstalled the old. Then it will automatically set the Environment PATH and install a module PyPDF2.

Please check whether everything installed.

Ghost Script: C://Program Files\gs\gs9.52...\bin (Something like this)
Tesseract: C://Program FIles\Tesseract-OCR (Also check in Command-Line whether Environment Path is set by this command **tesseract**)
And also the Python version in the command line.

If they all set perfectly it will work. Please let me know if there any errors.

**Comment by jayantanth** [comment]
![1](https://user-images.githubusercontent.com/1370149/86453953-369a7100-bd3c-11ea-8028-7df9512f1653.PNG)
![2](https://user-images.githubusercontent.com/1370149/86453958-38643480-bd3c-11ea-9281-9be7caba1dc4.PNG)
![3](https://user-images.githubusercontent.com/1370149/86453962-38fccb00-bd3c-11ea-8a8c-f17b86e045e7.PNG)
above three images of my all location..........................


![4](https://user-images.githubusercontent.com/1370149/86454183-81b48400-bd3c-11ea-8c93-3ba92f9898d5.PNG)
![5](https://user-images.githubusercontent.com/1370149/86454187-837e4780-bd3c-11ea-9a6c-7496cc8104c1.PNG)

Above two images of Environment Path , anything need to be add in Environment Path  extra???

**Comment by Parathantl** [comment]
@jayantanth No. These all looks fine. It should work. Because I tested in another Windows Installed PC today. 

Check for PyPDF2 module installed using pip.

`pip install PyPDF2`

Try this in command-line. 

Or run the **setup**.**bat** it will set all these.

**Comment by jayantanth** [comment]
Ok, I have found why the application is closed. It is working fine when I am adding the file less than 10MB. Anything 10MB+ file will be closed the application.

**Comment by Parathantl** [comment]
@jayantanth I think it would not be the issue. Maybe the PDF you are trying to OCR would be encrypted. Could you please share the PDF you are trying to OCR if possible?

Because I tried OCR a PDF with 62 MB.

**Comment by jayantanth** [comment]
Yes, you are right. My PDF file was locked by password to edit, export, print etc. Only view possible. The same file is working fine. So I think all is ok. Thanks for help and listen to my issues. This is very good tools for Windows User. :)

**Comment by Parathantl** [comment]
Great. Thank you so much.

Keep creating issues / adding any additional features to make this tool a better one.
