### ISSUE TITLE
add your YouTube video links in readme

### ISSUE THREAD

**Issue by tshrinivasan** [Parathantl/tesseract_gui#8]
Add the video links in readme.

**Comment by nithyadurai87** [comment]
https://www.youtube.com/watch?v=NSZmOYuEaOw

**Comment by nithyadurai87** [comment]
https://www.youtube.com/watch?v=awnGGLyYqec

**Comment by Parathantl** [comment]
https://www.youtube.com/watch?v=zenvLwzPg_w

**Comment by Parathantl** [comment]
Added 3 above videos in the read me file
